Better Test Driver

diff --git a/test/testDriver b/test/testDriver
--- a/test/testDriver
+++ b/test/testDriver
@@ -1,23 +1,27 @@
-#!/bin/bash
-for case in `ls *.cmdLine`; do
+#!/bin/bash 
+set -o pipefail
+
+for case in `ls test/*.cmdLine`; do
    base=`basename $case .cmdLine`
    echo 
    echo "RUNING: hello" `cat $case`
-   if [ ../hello `cat $case` | diff -q - ${base}.out ]; then
-   #a=${PIPESTATUS[0]}
-   #b=${PIPESTATUS[1]}
-   #echo $a, $b
-   #if [ $a -a $b ]; then
-      echo -e '\t success'
+   echo "------------------------"
+
+   hello `cat $case` | diff -q - test/${base}.out
+   res=$(( ${PIPESTATUS[0]}+${PIPESTATUS[1]} ))
+   echo ${res}
+   if [ ${res} -eq 0 ]; then
+      echo 'Success'
    else 
-      echo -e '\t Failed'
+      echo 'Failed'
       echo "Output should be"
-      cat ${base}.out
+      cat test/${base}.out
       echo
       echo "but was "
-      ../hello `cat $case`
+      hello `cat $case`
       exit 1
    fi
+   echo
 done
 
 exit 0
